; This file was auto-generated by drush make
core = 7.x

api = 2

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[varbase][download][type] = ""
;projects[varbase][download][url] = ""
;projects[varbase][type] = "module"

projects[backup_migrate][version] = "2.4"
projects[backup_migrate][subdir] = contrib

projects[bh_bootstrapextras][version] = "1.0-beta2"
projects[bh_bootstrapextras][subdir] = contrib

projects[ctools][version] = "1.2"
projects[ctools][subdir] = contrib

projects[context][version] = "3.0-beta4"
projects[context][subdir] = contrib

projects[date][version] = "2.6"
projects[date][subdir] = contrib

projects[ds][version] = "1.5"
projects[ds][subdir] = contrib

projects[entity][version] = "1.0-rc3"
projects[entity][subdir] = contrib

projects[extlink][version] = "1.12"
projects[extlink][subdir] = contrib

projects[features][version] = "1.0"
projects[features][subdir] = contrib

projects[field_group][version] = "1.1"
projects[field_group][subdir] = contrib

projects[media][version] = "1.2"
projects[media][subdir] = contrib

projects[filefield_paths][version] = "1.0-beta3"
projects[filefield_paths][subdir] = contrib

projects[globalredirect][version] = "1.5"
projects[globalredirect][subdir] = contrib

projects[google_analytics][version] = "1.2"
projects[google_analytics][subdir] = contrib

projects[googlenews][version] = "1.4"
projects[googlenews][subdir] = contrib

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[htmlpurifier][download][type] = "get"
libraries[htmlpurifier][download][url] = "http://htmlpurifier.org/releases/htmlpurifier-4.4.0.tar.gz"
libraries[htmlpurifier][directory_name] = "htmlpurifier"
libraries[htmlpurifier][type] = "library"

; Modules
projects[insert][version] = "1.2"
projects[insert][subdir] = contrib

projects[jquery_update][version] = "2.1+9-dev"
projects[jquery_update][subdir] = contrib

projects[libraries][version] = "2.0"
projects[libraries][subdir] = contrib

projects[link][version] = "1.0"
projects[link][subdir] = contrib

projects[menu_per_role][version] = "1.x-dev"
projects[menu_per_role][subdir] = contrib

projects[module_filter][version] = "1.7"
projects[module_filter][subdir] = contrib

projects[nodequeue][version] = "2.0-beta1"
projects[nodequeue][subdir] = contrib

projects[panels][version] = "3.3"
projects[panels][subdir] = contrib

projects[pathauto][version] = "1.2"
projects[pathauto][subdir] = contrib

projects[pdir][version] = "1.0"
projects[pdir][subdir] = contrib

projects[persistent_login][version] = "1.0-beta1"
projects[persistent_login][subdir] = contrib

projects[quicktabs][version] = "3.4"
projects[quicktabs][subdir] = contrib

projects[title][version] = "1.0-alpha4"
projects[title][subdir] = contrib

projects[token][version] = "1.3"
projects[token][subdir] = contrib

projects[transliteration][version] = "3.1"
projects[transliteration][subdir] = contrib

projects[views][version] = "3.5"
projects[views][subdir] = contrib

projects[webform][version] = "3.18"
projects[webform][subdir] = contrib

projects[wysiwyg][version] = "2.1+37-dev"
projects[wysiwyg][subdir] = contrib

; Themes
projects[bh_bootstrap][version] = "2.2+2-dev"

projects[rubik][version] = "4.0-beta8"
projects[rubik][subdir] = admin

projects[tao][version] = "3.0-beta4"
projects[tao][subdir] = admin

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[varbase_feature][download][type] = "get"
;projects[varbase_feature][download][url] = ""
;projects[varbase_feature][type] = "module"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;libraries[bootstrap][download][type] = "git"
;libraries[bootstrap][download][url] = "https://github.com/twitter/bootstrap.git"
;libraries[bootstrap][directory_name] = "bootstrap"
;libraries[bootstrap][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.4/ckeditor_3.6.4.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"


