; This file was auto-generated by drush make
core = 7.x

api = 2

; Modules
projects[backup_migrate][version] = "2.4"
projects[backup_migrate][subdir] = contrib

projects[ctools][version] = "1.2"
projects[ctools][subdir] = contrib

projects[coder][version] = "1.2"
projects[coder][subdir] = dev

projects[context][version] = "3.0-beta4"
projects[context][subdir] = contrib

projects[date][version] = "2.6"
projects[date][subdir] = contrib

projects[devel][version] = "1.3"
projects[devel][subdir] = dev

projects[ds][version] = "2.0"
projects[ds][subdir] = contrib

projects[entity][version] = "1.0-rc3"
projects[entity][subdir] = contrib

projects[entity_translation][version] = "1.0-beta1"
projects[entity_translation][subdir] = contrib

projects[entitycache][version] = "1.1"
projects[entitycache][subdir] = contrib

projects[entitycache_flush][version] = "1.1"
projects[entitycache_flush][subdir] = contrib

projects[entityreference][version] = "1.0-rc5"
projects[entityreference][subdir] = contrib

projects[extlink][version] = "1.12"
projects[extlink][subdir] = contrib

projects[features][version] = "1.0"
projects[features][subdir] = contrib

projects[field_group][version] = "1.1"
projects[field_group][subdir] = contrib

projects[media][version] = "1.2"
projects[media][subdir] = contrib

projects[filefield_paths][version] = "1.0-beta3"
projects[filefield_paths][subdir] = contrib

projects[redirect][version] = "1.0-rc1"
projects[redirect][subdir] = contrib

projects[google_analytics][version] = "1.3"
projects[google_analytics][subdir] = contrib

projects[googlenews][version] = "1.4"
projects[googlenews][subdir] = contrib

projects[htmlpurifier][version] = "1.0"
projects[htmlpurifier][subdir] = contrib

projects[i18n][version] = "1.7"
projects[i18n][subdir] = contrib

projects[jquery_update][version] = "2.x-dev"
projects[jquery_update][subdir] = contrib

projects[l10n_client][version] = "1.1"
projects[l10n_client][subdir] = contrib

projects[l10n_update][version] = "1.0-beta3"
projects[l10n_update][subdir] = contrib

projects[libraries][version] = "2.0"
projects[libraries][subdir] = contrib

projects[link][version] = "1.0"
projects[link][subdir] = contrib

projects[masquerade][version] = "1.0-rc5"
projects[masquerade][subdir] = dev

projects[memcache][version] = "1.0"
projects[memcache][subdir] = contrib

projects[menu_per_role][version] = "1.x-dev"
projects[menu_per_role][subdir] = contrib

projects[module_filter][version] = "1.7"
projects[module_filter][subdir] = dev

projects[metatag][version] = "1.0-beta2"
projects[metatag][subdir] = contrib

projects[nodequeue][version] = "2.0-beta1"
projects[nodequeue][subdir] = contrib

projects[panels][version] = "3.3"
projects[panels][subdir] = contrib

projects[pathauto][version] = "1.2"
projects[pathauto][subdir] = contrib

projects[pdir][version] = "1.0"
projects[pdir][subdir] = contrib

projects[quicktabs][version] = "3.4"
projects[quicktabs][subdir] = contrib

projects[recaptcha][version] = "1.8"
projects[recaptcha][subdir] = contrib

projects[remember_me][version] = "1.0"
projects[remember_me][subdir] = contrib

projects[site_verify][version] = "1.0"
projects[site_verify][subdir] = contrib

projects[strongarm][version] = "2.0"
projects[strongarm][subdir] = contrib

projects[title][version] = "1.0-alpha4"
projects[title][subdir] = contrib

projects[token][version] = "1.4"
projects[token][subdir] = contrib

projects[user_registrationpassword][version] = "1.3"
projects[user_registrationpassword][subdir] = contrib

projects[variable][version] = "2.1"
projects[variable][subdir] = contrib

projects[views][version] = "3.5"
projects[views][subdir] = contrib

projects[webform][version] = "3.18"
projects[webform][subdir] = contrib

projects[wysiwyg][version] = "2.2"
projects[wysiwyg][subdir] = contrib

projects[xmlsitemap][version] = "2.0-rc1"
projects[xmlsitemap][subdir] = contrib

; Themes
projects[twitter_bootstrap][version] = "2.0-beta1"

; Libraries
libraries[json2][download][type] = "get"
libraries[json2][download][url] = "https://github.com/douglascrockford/JSON-js/archive/master.tar.gz"
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"

libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.5/ckeditor_3.6.5.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

libraries[htmlpurifier][download][type] = "get"
libraries[htmlpurifier][download][url] = "http://htmlpurifier.org/releases/htmlpurifier-4.4.0.tar.gz"
libraries[htmlpurifier][directory_name] = "htmlpurifier"
libraries[htmlpurifier][type] = "library"
