<?php

/**
 * @file
 * Contains varbase_media.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\editor\Entity\Editor;

/**
 * Implements hook_page_attachments().
 */
function varbase_media_page_attachments(array &$page) {
  // Attached the varbase media common library.
  $page['#attached']['library'][] = 'varbase_media/common';

  if (!(\Drupal::currentUser()->isAnonymous())) {
    // Attached the varbase media common logged in users library.
    $page['#attached']['library'][] = 'varbase_media/common_logged';
  }
}

/**
 * Implements hook_ckeditor_css_alter().
 */
function varbase_media_ckeditor_css_alter(array &$css, Editor $editor) {

  // Attached the varbase media common style.
  $css[] = drupal_get_path('module', 'varbase_media') . '/css/varbase_media.common.css';

  // Attached the varbase media common logged in users style.
  $css[] = drupal_get_path('module', 'varbase_media') . '/css/varbase_media.common_logged.css';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function varbase_media_form_entity_embed_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Only at the embed step.
  if ($form_state->get('step') == 'embed') {

    // Get the entity values and attributes.
    $entity_element = empty($values['attributes']) ? array() : $values['attributes'];
    $entity_element += $form_state->get('entity_element');
    $form_state->set('entity_element', $entity_element);
    $entity = $form_state->get('entity');

    // Get the entity bundle type.
    $bundle_type = $entity->bundle();
    $values = $form_state->getValues();

    switch ($bundle_type) {
      case "image":

        // Adding the alt field to the embed dialog form.
        $form['attributes']['alt'] = [
          '#title' => t('Alternative text'),
          '#type' => 'textfield',
          '#required' => TRUE ,
          '#default_value' => $entity->field_image->alt,
          '#description' => t('This text will be used by screen readers, search engines, or when the image cannot be loaded.'),
        ];

        // Adding the title field to the embed dialog form.
        $form['attributes']['title'] = [
          '#title' => t('Title'),
          '#type' => 'textfield',
          '#default_value' => $entity->field_image->title,
          '#description' => t('The title is used as a tool tip when the user hovers the mouse over the image.'),
        ];

        // Render the Embed entity.
        $form['entity'] = [
          '#type' => 'item',
          '#markup' => \Drupal::service('renderer')->renderRoot(entity_view($entity, 's3')),
        ];

        // Change the "data align" field from rado buttons to Select list.
        $form['attributes']['data-align']['#type'] = 'select';
        $form['attributes']['data-align']['#wrapper_attributes'] = '';
        $form['attributes']['data-align'] += [
          '#description' => t('Choose the positioning of the image.'),
        ];

        // Add description for the caption field.
        $form['attributes']['data-caption'] += [
          '#description' => t('A caption will be displayed under the image, to describe it in context of your content.'),
        ];

        // Adding the updated alt text to the media entity.
        if (isset($entity_element['alt'])) {
          $entity->field_image->alt = $entity_element['alt'];
        }

        // Adding the updated title text to the media entity.
        if (isset($entity_element['title'])) {
          $entity->field_image->title = $entity_element['title'];
        }

        $entity->save();
        break;
    }
  }
}
