<?php

/**
 * @file
 * Contains varbase_core.module.
 */

// To have all varbase core general and global tokens.
module_load_include('inc', 'varbase_core', 'varbase_core.tokens');

/**
 * Implements hook_FORM_ID_form_alter.
 */
function varbase_core_form_node_form_alter(&$form, $form_state) {
  // Override node form sidebar order.
  if (isset($form['author'])) {
    $form['author']['#weight'] = -6;
  }
  if (isset($form['field_comments'])) {
    $form['field_comments']['widget'][0]['#weight'] = -5;
  }
  if (isset($form['path_settings'])) {
    $form['path_settings']['#weight'] = -4;
  }
  if (isset($form['field_meta_tags'])) {
    $form['field_meta_tags']['widget'][0]['#weight'] = -3;
  }
  if (isset($form['simple_sitemap'])) {
    $form['simple_sitemap']['#weight'] = -2;
  }
  if (isset($form['ds_switch_view_mode'])) {
    $form['ds_switch_view_mode']['#weight'] = 101;
  }
}
