<?php

/**
 * @file
 * Contains varbase_seo.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function varbase_seo_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['field_yoast_seo']) &&
      isset($form['field_yoast_seo']['widget']) &&
      isset($form['field_yoast_seo']['widget']['0']) &&
      isset($form['field_yoast_seo']['widget']['0']['yoast_seo'])) {
    $form['field_yoast_seo']['widget']['0']['yoast_seo']['#title'] = t('Real-time SEO analyzer');
  }
}
